### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by NyaomiDEV** [ItalianDevs4PM/CustomJoin#1]
- [x] Fare una lista To-Do (_easter egg portami via_)
- [ ] Integrazione con CustomAlerts
- [ ] Diversi rank settabili nelle config (proposta)
- [ ] Bugfix
